### ISSUE TITLE
Timeout for elections 

### ISSUE THREAD

**Issue by guhur** [MieuxVoter/mvapi#9]
We should add a time out to automatically close and start elections.

This needs to adapt the:

- [ ] the model in order to include a starting and ending date to an election;
- [ ] the docker to add cron tasks that check the time outs;
- [ ] tests for the updated models and the cron tasks.

**Comment by sebsheep** [comment]
I'm not sure cron task will be necessary: say we have a vote at the url /vote/1, which begins at 10:00 and ends at 11:00.

When someone asks for /vote/1, display "Vote is not started yet!/Please grade the choices/The vote is over, here are the results" depending of the current time. Crontasks would make the server more difficult to understand due to "hidden side effects".

**Comment by guhur** [comment]
I agree with you but I think we'll need cron tasks anyway to send emails to voters with a link to the results, right?

Do you think we should split this issue into 2 parts then?

**Comment by sebsheep** [comment]
Agreed for the email to send results handled by a cron task. Agreed to split this into 2 issues : 
* this one to add the time limitation
* another one to add a cron which just send an email

**Comment by guhur** [comment]
OK ! We'll open the second issue when this one will be resolved to avoid duplications.
